---
services:
  knight:
    image: ghcr.io/blue-army-2017/knight:main
    container_name: knight
    volumes:
      - ./knight.db:/knight.db
    networks:
      - knight

  knight-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.6.0
    command: --config /oauth2-proxy.cfg
    container_name: knight-proxy
    ports:
      - 8080:4180
    volumes:
      - ./oauth2-proxy.cfg:/oauth2-proxy.cfg
    networks:
      - knight
    depends_on:
      - knight

networks:
  knight:
