# https://taskfile.dev
---
version: "3"

tasks:
  run:
    cmds:
      - go run .
    silent: true
    deps:
      - download-assets
  build:
    cmds:
      - go build .
    silent: true
    deps:
      - download-assets

  format:
    cmds:
      - go fmt ./...
  lint:
    cmds:
      - go vet ./...
  test:
    cmds:
      - go test ./...

  download-assets:
    cmds:
      - ./assets/download.sh
    sources:
      - assets/download.sh
    generates:
      - assets/css/pico.css
    silent: true
