# https://taskfile.dev
---
version: "3"

tasks:
  default:
    cmd: go run .

  build:
    cmd: go build

  test:
    cmd: go test ./...
    env:
      DB_NAME: ":memory:"

  coverage:
    cmd: go test -coverprofile cover.out ./...
    env:
      DB_NAME: ":memory:"

  migrate:
    cmd: go run ./migration knight.db ./migration/legacy-data.json
