# https://taskfile.dev
---
version: "3"

tasks:
  default:
    cmd: go run .
    env:
      DB_NAME: db/knight.db

  build:
    cmd: go build

  test:
    cmd: go test ./...
    env:
      DB_NAME: ":memory:"

  coverage:
    cmd: go test -coverprofile cover.out ./...
    env:
      DB_NAME: ":memory:"

  migrate:
    cmd: go run ./migration db/knight.db ./migration/legacy-data.json

  db-create-migration:
    cmd: migrate create -ext sql -dir schema -seq {{.CLI_ARGS}}

  db-run-migrations:
    cmd: migrate -database sqlite3://db/knight.db -path schema up
